Add files via upload
MichiasShiferaw/database-proj pull request #16
Opened 2023-03-14 17:13 UTC by AlexSteeves

Initial design of database, currently does not compile, I'm having a problem with foreign keys in the employees table referencing address info. The attribute values are also not correct I've set everything to VARCHAR during compilation.

2023-03-14 21:38 UTC, MichiasShiferaw commented on InitialDatabaseSQL.sql
> +	street_name VARCHAR(20) NOT NULL,
Change to VARCHAR(30)

2023-03-14 21:39 UTC, MichiasShiferaw commented on InitialDatabaseSQL.sql
> +    street_number INT NOT NULL CHECK (street_number >= 0),
Change to SMALLINT

2023-03-14 21:39 UTC, MichiasShiferaw commented on InitialDatabaseSQL.sql
> +	PRIMARY KEY(street_name, street_number, postal_code)
Remove the excess indent

2023-03-14 21:39 UTC, MichiasShiferaw commented on InitialDatabaseSQL.sql
> +	emp_SSN VARCHAR(20) NOT NULL,
remove the excess indent

2023-03-14 21:40 UTC, MichiasShiferaw commented on InitialDatabaseSQL.sql
> +    street_number INT NOT NULL CHECK (street_number >= 0),
Change to SMALLINT

2023-03-14 21:40 UTC, MichiasShiferaw commented on InitialDatabaseSQL.sql
> +    street_name VARCHAR(20) NOT NULL,
Change to VARCHAR(30)

2023-03-14 21:41 UTC, MichiasShiferaw commented on InitialDatabaseSQL.sql
> +
Use

`FOREIGN KEY (street_name, street_number, postal_code) REFERENCES address_info(street_name, street_number, postal_code)`

2023-03-14 21:43 UTC, MichiasShiferaw commented
> Initial design of database, currently does not compile, I'm having a problem with foreign keys in the employees table referencing address info.

Should be solved with
`FOREIGN KEY (street_name, street_number, postal_code) REFERENCES address_info(street_name, street_number, postal_code)`

2023-03-15 02:14 UTC, MichiasShiferaw commented on InitialDatabaseSQL.sql
> +    hotel_id VARCHAR(20),
Add NOT NULL for remaining attributes

2023-03-15 02:15 UTC, MichiasShiferaw commented on InitialDatabaseSQL.sql
> +    Primary Key(emp_SSN),
Should be 
Primary Key(emp_SSN, role_id),

2023-03-15 02:16 UTC, MichiasShiferaw commented on InitialDatabaseSQL.sql
> +CREATE TABLE customer(
make sure customer's datatypes are similar to employees

2023-03-15 02:17 UTC, MichiasShiferaw commented on InitialDatabaseSQL.sql
> +	chain_id VARCHAR(20)  NOT NULL,
CHAR(3)

2023-03-15 02:17 UTC, MichiasShiferaw commented on InitialDatabaseSQL.sql
> +	chain_id VARCHAR(20)  NOT NULL,
CHAR(3)

2023-03-15 02:18 UTC, MichiasShiferaw commented on InitialDatabaseSQL.sql
> +    PRIMARY KEY(chain_id),
Correct to
PRIMARY KEY(chain_id,hotel_id),

2023-03-15 02:18 UTC, MichiasShiferaw commented on InitialDatabaseSQL.sql
> +    PRIMARY KEY(hotel_id),
PRIMARY KEY(chain_id,hotel_id),

2023-03-15 02:20 UTC, MichiasShiferaw commented on InitialDatabaseSQL.sql
> +    FOREIGN KEY(hotel_id) REFERENCES booking_info(hotel_id),
REFERENCES hotel.hotel_id and not booking_info

2023-03-15 02:21 UTC, MichiasShiferaw commented on InitialDatabaseSQL.sql
> +    FOREIGN KEY(employee_SSN) REFERENCES employee(employee_SSN)
FOREIGN KEY(emp_SSN) REFERENCES employee(emp_SSN)

2023-03-15 02:21 UTC, MichiasShiferaw commented on InitialDatabaseSQL.sql
> +    FOREIGN KEY(customer_SSN) REFERENCES employee(emp_SSN),
FOREIGN KEY(customer_SSN) REFERENCES customer(customer_SSN),

2023-03-15 02:21 UTC, MichiasShiferaw commented on InitialDatabaseSQL.sql
> +    FOREIGN KEY(room_no) REFERENCES room(room_no)
FOREIGN KEY(hotel_id,room_no) REFERENCES room(hotel_id,room_no)

2023-03-15 02:35 UTC, MichiasShiferaw commented on InitialDatabaseSQL.sql
> +DROP TABLE address_info;
For organization, have all the drop tables at the top as such,

drop table hotel_chain;
drop table hotel_phone;

drop table renting_info;
drop table booking_info;
drop table customer;
drop table role;

drop table room;
drop table hotel;
drop table employee;
drop table room_category;
drop table address_info;

2023-03-15 02:35 UTC, MichiasShiferaw commented on InitialDatabaseSQL.sql
> +    FOREIGN KEY(street_name) references address_info(street_name),
https://github.com/MichiasShiferaw/database-proj/pull/16/commits/b950a9ad4889d03c623a0c89fb996d5c1233aee7#r1136243720

2023-03-15 02:36 UTC, MichiasShiferaw commented on InitialDatabaseSQL.sql
> +    FOREIGN KEY(employee_SSN) REFERENCES employee(employee_SSN)
Also add
`FOREIGN KEY(hotel_id,room_no) REFERENCES room(hotel_id,room_no)`

2023-03-15 02:36 UTC, MichiasShiferaw commented on InitialDatabaseSQL.sql
> +    FOREIGN KEY(hotel_id) REFERENCES hotel(hotel_id),
`    FOREIGN KEY(hotel_id,room_no) REFERENCES room(hotel_id,room_no)`

2023-03-15 02:36 UTC, MichiasShiferaw commented on InitialDatabaseSQL.sql
> +    FOREIGN KEY(hotel_id) REFERENCES hotel(hotel_id),
Remove that line for this one

2023-03-15 02:37 UTC, MichiasShiferaw commented on InitialDatabaseSQL.sql
> +    FOREIGN KEY(emp_SSN) REFERENCES employee(emp_SNN),
emp_SSN** not emp_SNN

2023-03-18 21:05 UTC, kevinluong21 requested changes
The chain_name, email, and province need to be longer than 20 (50 should work on the data I want to insert)

2023-03-18 21:22 UTC, kevinluong21 requested changes
- The chain_name, email, and province need to be longer than 20 (50 should work on the data I want to insert)
- if manager SSN must be not null when inserting hotel, it means that i have to insert a manager first, but hotel ID must be not null when inserting an employee, but you can't insert a hotel first. basically it's impossible to insert.

2023-03-20 12:22 UTC, MichiasShiferaw approved these changes

2023-03-29 03:08 UTC, kevinluong21 requested changes
Could the hotel_name attribute in hotel be extended to 100 characters?

2023-04-03 02:30 UTC, kevinluong21 commented
Can the prices for the rooms be changed to DECIMAL(6, 2) instead to accomodate for prices $100 and above?

2023-04-03 13:34 UTC, merged